//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Properties.Locales {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Properties.Locales.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Show application infos. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string about_app_summary {
            get {
                return ResourceManager.GetString("about_app_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About App benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string about_app_text {
            get {
                return ResourceManager.GetString("about_app_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculator benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string contact_text {
            get {
                return ResourceManager.GetString("contact_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DEL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string del_text {
            get {
                return ResourceManager.GetString("del_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string lang_name {
            get {
                return ResourceManager.GetString("lang_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string settings_text {
            get {
                return ResourceManager.GetString("settings_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string version_text {
            get {
                return ResourceManager.GetString("version_text", resourceCulture);
            }
        }
    }
}
